"""converte coluna 'number' em única

Revision ID: 06581c1a3e10
Revises: 44040ff9dd08
Create Date: 2025-05-11 21:57:36.949609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06581c1a3e10'
down_revision = '44040ff9dd08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
