"""altera responsible

Revision ID: 13538639d8b4
Revises: e9763ed4d1e1
Create Date: 2025-05-26 16:56:25.106450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13538639d8b4'
down_revision = 'e9763ed4d1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responsible', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship_with_elderly', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('primary_need_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('preferred_contact_method', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responsible', schema=None) as batch_op:
        batch_op.drop_column('preferred_contact_method')
        batch_op.drop_column('primary_need_description')
        batch_op.drop_column('relationship_with_elderly')

    # ### end Alembic commands ###
