"""update 2

Revision ID: 171fe98fa338
Revises: dbb8f071b43e
Create Date: 2025-06-02 02:36:10.080605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171fe98fa338'
down_revision = 'dbb8f071b43e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sadad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sadad', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
