"""aumentar tamanho de textos em caregivers

Revision ID: 88e77b6b2ef9
Revises: 3d3dbbf32321
Create Date: 2025-05-27 19:38:35.965550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e77b6b2ef9'
down_revision = '3d3dbbf32321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caregiver', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caregiver', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
