"""adicionar_campos_endereco_detalhados

Revision ID: 971c0a66798a
Revises: 435cd8338c78
Create Date: 2025-06-04 02:16:12.006625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971c0a66798a'
down_revision = '435cd8338c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elderly', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cep_elderly', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('number_elderly', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('neighborhood_elderly', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('complement_elderly', sa.String(length=100), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cep', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('neighborhood', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('complement', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('complement')
        batch_op.drop_column('neighborhood')
        batch_op.drop_column('number')
        batch_op.drop_column('cep')

    with op.batch_alter_table('elderly', schema=None) as batch_op:
        batch_op.drop_column('complement_elderly')
        batch_op.drop_column('neighborhood_elderly')
        batch_op.drop_column('number_elderly')
        batch_op.drop_column('cep_elderly')

    # ### end Alembic commands ###
