"""altera o elderly

Revision ID: c444993b7172
Revises: 13538639d8b4
Create Date: 2025-05-26 17:17:02.750042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c444993b7172'
down_revision = '13538639d8b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elderly', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('cpf', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address_elderly', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city_elderly', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state_elderly', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('medical_conditions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('medications_in_use', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mobility_level', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('specific_care_needs', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_relationship', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('health_plan_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('health_plan_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('additional_notes', sa.Text(), nullable=True))
        batch_op.drop_constraint('elderly_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elderly', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('elderly_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('additional_notes')
        batch_op.drop_column('health_plan_number')
        batch_op.drop_column('health_plan_name')
        batch_op.drop_column('emergency_contact_relationship')
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('specific_care_needs')
        batch_op.drop_column('mobility_level')
        batch_op.drop_column('medications_in_use')
        batch_op.drop_column('allergies')
        batch_op.drop_column('medical_conditions')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('state_elderly')
        batch_op.drop_column('city_elderly')
        batch_op.drop_column('address_elderly')
        batch_op.drop_column('cpf')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
