"""alteração em caregivers

Revision ID: e938d84f0209
Revises: 97ab52cf200a
Create Date: 2025-05-26 16:43:29.634038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e938d84f0209'
down_revision = '97ab52cf200a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caregiver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dias_disponiveis', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('periodos_disponiveis', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('inicio_imediato', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pretensao_salarial', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caregiver', schema=None) as batch_op:
        batch_op.drop_column('pretensao_salarial')
        batch_op.drop_column('inicio_imediato')
        batch_op.drop_column('periodos_disponiveis')
        batch_op.drop_column('dias_disponiveis')

    # ### end Alembic commands ###
