"""campos adicionais no contrato

Revision ID: f825fafcaa0c
Revises: 88e77b6b2ef9
Create Date: 2025-05-30 02:08:41.418042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f825fafcaa0c'
down_revision = '88e77b6b2ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('monthly_salary', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('payment_frequency', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('work_schedule', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('special_conditions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('special_conditions')
        batch_op.drop_column('work_schedule')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('payment_frequency')
        batch_op.drop_column('monthly_salary')
        batch_op.drop_column('hourly_rate')

    # ### end Alembic commands ###
